import { GalleryType } from "@/types";

export const Galleries:GalleryType[] = [
  {
    id: "1",
    name: "123 The Best",
    image: "/images/Categorized_Gallery/logo_design/logo_design_01.webp",
    cat: "Logo Design",
  },
  {
    id: "2",
    name: "True Colors",
    image: "/images/Categorized_Gallery/logo_design/logo_design_02.webp",
    cat: "Logo Design",
  },
  {
    id: "3",
    name: "Jo Jo's Bar and Grill",
    image: "/images/Categorized_Gallery/logo_design/logo_design_03.webp",
    cat: "Logo Design",
  },
  {
    id: "4",
    name: "Ocean View",
    image: "/images/Categorized_Gallery/logo_design/logo_design_04.webp",
    cat: "Logo Design",
  },
  {
    id: "5",
    name: "Keep It Kiwi",
    image: "/images/Categorized_Gallery/logo_design/logo_design_05.webp",
    cat: "Logo Design",
  },
  {
    id: "6",
    name: "Jiggy",
    image: "/images/Categorized_Gallery/logo_design/logo_design_06.webp",
    cat: "Logo Design",
  },
  {
    id: "7",
    name: "Frosty Island",
    image: "/images/Categorized_Gallery/logo_design/logo_design_07.webp",
    cat: "Logo Design",
  },
  {
    id: "8",
    name: "Chilly Willy's",
    image: "/images/Categorized_Gallery/logo_design/logo_design_08.webp",
    cat: "Logo Design",
  },
  {
    id: "9",
    name: "Daisy",
    image: "/images/Categorized_Gallery/Ecommerce_Website/ecommerce_website_01.webp",
    cat: "Ecommerce Solutions",
  },
  {
    id: "10",
    name: "Food Pean",
    image: "/images/Categorized_Gallery/Ecommerce_Website/ecommerce_website_02.webp",
    cat: "Ecommerce Solutions",
  },
  {
    id: "11",
    name: "The Bombeno Group",
    image: "/images/Categorized_Gallery/Ecommerce_Website/ecommerce_website_03.webp",
    cat: "Ecommerce Solutions",
  },
  {
    id: "12",
    name: "Pets Watch",
    image: "/images/Categorized_Gallery/Ecommerce_Website/ecommerce_website_04.webp",
    cat: "Ecommerce Solutions",
  },
  {
    id: "13",
    name: "Hauzz",
    image: "/images/Categorized_Gallery/Ecommerce_Website/ecommerce_website_05.webp",
    cat: "Ecommerce Solutions",
  },
  {
    id: "14",
    name: "Heritag",
    image: "/images/Categorized_Gallery/Ecommerce_Website/ecommerce_website_06.webp",
    cat: "Ecommerce Solutions",
  },
  {
    id: "15",
    name: "Fortisi",
    image: "/images/Categorized_Gallery/Ecommerce_Website/ecommerce_website_07.webp",
    cat: "Ecommerce Solutions",
  },
  {
    id: "16",
    name: "Lancome",
    image: "/images/Categorized_Gallery/Ecommerce_Website/ecommerce_website_08.webp",
    cat: "Ecommerce Solutions",
  },
  {
    id: "18",
    name: "Insect",
    image: "/images/Categorized_Gallery/Illustration/illustration_01.webp",
    cat: "Illustration",
  },
  {
    id: "19",
    name: "Fly in Cardboard",
    image: "/images/Categorized_Gallery/Illustration/illustration_02.webp",
    cat: "Illustration",
  },
  {
    id: "20",
    name: "Female Style",
    image: "/images/Categorized_Gallery/Illustration/illustration_03.webp",
    cat: "Illustration",
  },
  {
    id: "21",
    name: "Female Glasses",
    image: "/images/Categorized_Gallery/Illustration/illustration_04.webp",
    cat: "Illustration",
  },
  {
    id: "22",
    name: "Faces of City",
    image: "/images/Categorized_Gallery/Illustration/illustration_05.webp",
    cat: "Illustration",
  },
  {
    id: "23",
    name: "Glass City in Polution",
    image: "/images/Categorized_Gallery/Illustration/illustration_06.webp",
    cat: "Illustration",
  },
  {
    id: "24",
    name: "Red Wine",
    image: "/images/Categorized_Gallery/Illustration/illustration_07.webp",
    cat: "Illustration",
  },
  {
    id: "25",
    name: "Black and White Life",
    image: "/images/Categorized_Gallery/Illustration/illustration_08.webp",
    cat: "Illustration",
  },
  {
    id: "26",
    name: "Wild Bars",
    image: "/images/Categorized_Gallery/Marketing_Collateral/marketing_collateral_01.webp",
    cat: "Marketing Collateral",
  },
  {
    id: "27",
    name: "My Blue Zone",
    image: "/images/Categorized_Gallery/Marketing_Collateral/marketing_collateral_02.webp",
    cat: "Marketing Collateral",
  },
  {
    id: "28",
    name: "ANIN",
    image: "/images/Categorized_Gallery/Marketing_Collateral/marketing_collateral_03.webp",
    cat: "Marketing Collateral",
  },
  {
    id: "29",
    name: "UKIO",
    image: "/images/Categorized_Gallery/Marketing_Collateral/marketing_collateral_04.webp",
    cat: "Marketing Collateral",
  },
  {
    id: "30",
    name: "OCC",
    image: "/images/Categorized_Gallery/Marketing_Collateral/marketing_collateral_05.webp",
    cat: "Marketing Collateral",
  },
  {
    id: "31",
    name: "Collation GEDEON",
    image: "/images/Categorized_Gallery/Marketing_Collateral/marketing_collateral_06.webp",
    cat: "Marketing Collateral",
  },
  {
    id: "32",
    name: "SurfCoffe",
    image: "/images/Categorized_Gallery/Marketing_Collateral/marketing_collateral_07.webp",
    cat: "Marketing Collateral",
  },
  {
    id: "33",
    name: "Gartenhonig",
    image: "/images/Categorized_Gallery/Marketing_Collateral/marketing_collateral_08.webp",
    cat: "Marketing Collateral",
  },
  {
    id: "34",
    name: "Gym Exrcise",
    image: "/images/Categorized_Gallery/Video_Animation/video_animation_01.webp",
    cat: "Animation",
  },
  {
    id: "35",
    name: "Success Rocket Launch",
    image: "/images/Categorized_Gallery/Video_Animation/video_animation_02.webp",
    cat: "Animation",
  },
  {
    id: "36",
    name: "Delivery",
    image: "/images/Categorized_Gallery/Video_Animation/video_animation_03.webp",
    cat: "Animation",
  },
  {
    id: "37",
    name: "Ship Sailing",
    image: "/images/Categorized_Gallery/Video_Animation/video_animation_04.webp",
    cat: "Animation",
  },
  {
    id: "38",
    name: "Software Development",
    image: "/images/Categorized_Gallery/Video_Animation/video_animation_05.webp",
    cat: "Animation",
  },
  {
    id: "39",
    name: "Man Dancing",
    image: "/images/Categorized_Gallery/Video_Animation/video_animation_06.webp",
    cat: "Animation",
  },
  {
    id: "40",
    name: "Price Stats",
    image: "/images/Categorized_Gallery/Video_Animation/video_animation_07.webp",
    cat: "Animation",
  },
  {
    id: "41",
    name: "Presentation",
    image: "/images/Categorized_Gallery/Video_Animation/video_animation_08.webp",
    cat: "Animation",
  },
  {
    id: "42",
    name: "Game Zone",
    image: "/images/Categorized_Gallery/Website_Design/website_design_01.webp",
    cat: "Website Design",
  },
  {
    id: "43",
    name: "Gym App",
    image: "/images/Categorized_Gallery/Website_Design/website_design_02.webp",
    cat: "Website Design",
  },
  {
    id: "44",
    name: "Hip Hop App",
    image: "/images/Categorized_Gallery/Website_Design/website_design_03.webp",
    cat: "Website Design",
  },
  {
    id: "45",
    name: "Vastrum",
    image: "/images/Categorized_Gallery/Website_Design/website_design_04.webp",
    cat: "Website Design",
  },
  {
    id: "46",
    name: "Free Leytics",
    image: "/images/Categorized_Gallery/Website_Design/website_design_05.webp",
    cat: "Website Design",
  },
  {
    id: "47",
    name: "Fit Less Coach",
    image: "/images/Categorized_Gallery/Website_Design/website_design_06.webp",
    cat: "Website Design",
  },
  {
    id: "48",
    name: "Dotaz",
    image: "/images/Categorized_Gallery/Website_Design/website_design_07.webp",
    cat: "Website Design",
  },
  {
    id: "50",
    name: "Beauty Beast",
    image: "/images/Categorized_Gallery/Website_Design/website_design_08.webp",
    cat: "Website Design",
  },
  {
    id: "51",
    name: "Pinkish Stats App",
    image: "/images/Categorized_Gallery/Mobile_Apps/mobile_apps_01.png",
    cat: "Mobile Apps",
  },
  {
    id: "52",
    name: "Dark Stats App",
    image: "/images/Categorized_Gallery/Mobile_Apps/mobile_apps_02.png",
    cat: "Mobile Apps",
  },
  {
    id: "53",
    name: "Butterfly App",
    image: "/images/Categorized_Gallery/Mobile_Apps/mobile_apps_03.png",
    cat: "Mobile Apps",
  },
  {
    id: "54",
    name: "Fitness App",
    image: "/images/Categorized_Gallery/Mobile_Apps/mobile_apps_04.png",
    cat: "Mobile Apps",
  },
  {
    id: "55",
    name: "Game Season App",
    image: "/images/Categorized_Gallery/Mobile_Apps/mobile_apps_05.png",
    cat: "Mobile Apps",
  },
  {
    id: "56",
    name: "Montly Income Goal App",
    image: "/images/Categorized_Gallery/Mobile_Apps/mobile_apps_06.png",
    cat: "Mobile Apps",
  },
  {
    id: "57",
    name: "Music Player App",
    image: "/images/Categorized_Gallery/Mobile_Apps/mobile_apps_07.png",
    cat: "Mobile Apps",
  },
  {
    id: "58",
    name: "File Explorer App",
    image: "/images/Categorized_Gallery/Mobile_Apps/mobile_apps_08.png",
    cat: "Mobile Apps",
  },
];